[package]
name = "aws_config_generator"
version = "0.1.0"
authors = ["Alan Jenkins <alan.james.jenkins@gmail.com>"]
edition = "2021"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.12.0"
aws-sdk-organizations = "0.12.0"
aws-sdk-sts = "0.12.0"
clap = "3.1"
dirs = "4.0"
lazy_static = "1.4.0"
tera = "1.15.0"
tokio = { version = "1.18", features = ["full"] }
toml = "0.5"
