[package]
name = "aws_config_generator"
version = "0.1.0"
authors = ["Alan Jenkins <alan.james.jenkins@gmail.com>"]
edition = "2018"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
dirs = "3.0"
rusoto_core = { version = "0.46.0", default_features = false, features = ["rustls"] }
rusoto_organizations = { version = "0.46.0", default_features = false, features = ["rustls"] }
rusoto_sts = { version = "0.46.0", default_features = false, features = ["rustls"] }
tokio = { version = "1.5.0", features = ["full"] }
toml = "0.5"
