name: Linux
on:
  release:
    types: [published, created, edited]

jobs:
  build-linux-x86_64:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: mad9000/actions-find-and-replace-string@2
        with:
            source: ${{ github.ref }}
            find: 'AWS_CONFIG_GENERATOR_VERSION'
            replace: ${{ github.ref }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/aws-config-generator
          asset_name: aws-config-generator-linux-x86_64
          tag: build-${{ github.ref }}

  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mad9000/actions-find-and-replace-string@2
        with:
            source: ${{ github.ref }}
            find: 'AWS_CONFIG_GENERATOR_VERSION'
            replace: ${{ github.ref }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/aws-config-generator
          asset_name: aws-config-generator-linux-armv7
          tag: build-${{ github.ref }}

  linux_arm64:
    name: Linux arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mad9000/actions-find-and-replace-string@2
        with:
            source: ${{ github.ref }}
            find: 'AWS_CONFIG_GENERATOR_VERSION'
            replace: ${{ github.ref }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/aws-config-generator
          asset_name: aws-config-generator-linux-arm64
          tag: build-${{ github.ref }}
