name: Linux Actions
on:
  tags:
    - v*
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  build-linux-x86_64:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - echo "Building ${{ github.ref }} for Linux x86_64."
      - name: Check out repository code
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/aws-config-generator
          asset_name: aws-config-generator-linux-x86_64
          tag: build-${{ github.ref }}

  linux_arm7:
      name: Linux ARMv7
      runs-on: ubuntu-latest
      steps:
        - echo "Building ${{ github.ref }} for Linux ARMv7."
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            target: armv7-unknown-linux-gnueabihf
            override: true
        - uses: actions-rs/cargo@v1
          with:
            use-cross: true
            command: build
            args: --target armv7-unknown-linux-gnueabihf
        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v1-release
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: target/release/aws-config-generator
            asset_name: aws-config-generator-linux-armv7
            tag: build-${{ github.ref }}

  linux_arm64:
      name: Linux arm64
      runs-on: ubuntu-latest
      steps:
        - echo "Building ${{ github.ref }} for Linux arm64."
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            target: aarch64-unknown-linux-gnu
            override: true
        - uses: actions-rs/cargo@v1
          with:
            use-cross: true
            command: build
            args: --target aarch64-unknown-linux-gnu
        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v1-release
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: target/release/aws-config-generator
            asset_name: aws-config-generator-linux-arm64
            tag: build-${{ github.ref }}
